//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayAdminModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class coreDevPageQuery
    {
        public int PAGE_ID { get; set; }
        public string PAGE_FIELD { get; set; }
        public string ANA_DESC { get; set; }
        public Nullable<bool> ANA_ACTIVE { get; set; }
        public Nullable<int> ANA_SORT { get; set; }
        public string ANA_CONTROLTYPE { get; set; }
        public Nullable<short> ANA_LENGTH { get; set; }
        public Nullable<bool> ANA_ISRANGE { get; set; }
        public string ANA_BEGINDATA { get; set; }
        public string ANA_ENDDATA { get; set; }
        public Nullable<bool> ANA_ISMUSTFIELD { get; set; }
        public Nullable<int> ANA_ISWHERE { get; set; }
        public Nullable<byte> ANA_SHOWOP { get; set; }
        public string ANA_TAG { get; set; }
    }
}
