//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayAdminModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class coreToolBarEvent
    {
        public int toolBarID { get; set; }
        public string toolBarEvent { get; set; }
        public string EventDataSource { get; set; }
        public string EventJS { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
