//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayAdminModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class coreDevPage
    {
        public int pageID { get; set; }
        public string pageQueryURL { get; set; }
        public string pageModifyURL { get; set; }
        public string pageTitle { get; set; }
        public string pageDataSource { get; set; }
        public string pageModifySource { get; set; }
        public string pageQueryFields { get; set; }
        public string pageWhereExpress { get; set; }
        public string pageEditWhere { get; set; }
        public string pageOrderBy { get; set; }
        public string pageColomns { get; set; }
        public string pageSearch { get; set; }
        public string pageEdit { get; set; }
        public string pageAdd { get; set; }
        public string pageDef { get; set; }
        public Nullable<int> pageToolBarID { get; set; }
        public Nullable<int> pageRowBarID { get; set; }
        public Nullable<int> pageLimit { get; set; }
        public string pageLimits { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
