//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using LayAdminModels;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class LayAdminEntities : DbContext
{
    public LayAdminEntities()
        : base("name=LayAdminEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<coreToolBar> coreToolBar { get; set; }
    public virtual DbSet<coreToolBarEvent> coreToolBarEvent { get; set; }
    public virtual DbSet<coreDevPage> coreDevPage { get; set; }
    public virtual DbSet<coreMenu> coreMenu { get; set; }
    public virtual DbSet<coreDevPageQuery> coreDevPageQuery { get; set; }
}
